# Generated by Django 4.2.6 on 2023-11-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.AddField(
            model_name='posts',
            name='categories',
            field=models.ManyToManyField(to='desk_app.categories'),
        ),
        migrations.AddField(
            model_name='posts',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='desk_app.publisher'),
        ),
    ]
