# Generated by Django 4.2.6 on 2023-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='categories',
            field=models.ManyToManyField(related_name='posts_for_cat', to='desk_app.categories'),
        ),
    ]
